// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: { path: "prisma/migrations" },
  datasource: {
    url: "postgresql://092217ef3a85104fb1d3a6b0b33e523beb082967052d03b73ce4647103313c7d:sk_VcmuIcU-DN2IGJFa5naVX@db.prisma.io:5432/postgres?sslmode=require",
  },
});
